name: diun

services:
  diun:
    image: crazymax/diun:latest
    command: serve
    volumes:
      - "./data:/data"
      - "./diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      TZ: Etc/UTC
      LOG_LEVEL: info
      LOG_JSON: false
    restart: always

networks:
  default:
    name: diun-network
